language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-with-require' ]; then cd .. && eval "mv $currentfolder generator-angular-with-require" && cd generator-angular-with-require; fi

